name: aoc
version: 2022.0
description: Please see the README on GitHub at <https://github.com/farbodsz/aoc#readme>
github: "farbodsz/aoc-2022"
author: "Farbod Salamat-Zadeh"
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc
